AWSTemplateFormatVersion: '2010-09-09'
Description: Security groups for the VPC

Resources:
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PublicSecurityGroup
      GroupDescription: Security group for public access
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PrivateSecurityGroup
      GroupDescription: Security group for private access
      VpcId: !ImportValue VPCID
